version: "3.8"

services:
  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka-kraft
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     KAFKA_PROCESS_ROLES: broker,controller
  #     KAFKA_NODE_ID: 1
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
  #     KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_CFG_NODE_ID: 1
  #     KAFKA_KRAFT_CLUSTER_ID: "my-kafka-cluster-id"
  #   volumes:
  #     - ./data/kafka:/tmp/kraft-combined-logs
  #   networks:
  #     backend:


  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local-kraft
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: "" # KRaft 모드이므로 ZK 사용 안 함
  #   depends_on:
  #     - kafka
  #   networks:
  #     backend:

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cheonkyu
      MYSQL_DATABASE: cheonkyu
      MYSQL_USER: cheonkyu
      MYSQL_PASSWORD: cheonkyu
    # volumes:
    #   - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend: